### ISSUE TITLE
Eufy Security - Configuration failed when restarting HOST VM Home Assistant

### ISSUE THREAD

**Issue by SmartM-ui** [fuatakgun/eufy_security#252]
Hi @fuatakgun ,
when I restart the Home Assistant VM (so not the simple restart, but the restart of the Host),
the integration reports that there was a configuration error:

<img width="214" alt="Schermata 2022-02-02 alle 10 56 42" src="https://user-images.githubusercontent.com/63554131/152136944-9b37d47f-bbca-4358-a884-40bef6174881.png">

In the logs I can see these errors:

```
Logger: homeassistant.config_entries
Source: config_entries.py:344
First occurred: 10:55:19 (2 occurrences)
Last logged: 10:55:25

Config entry 'MYIPxxx' for eufy_security integration not ready yet: Exception: Host/port is not reachable MYIPxxx 3000!; Retrying in background
```

```
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant.config_entries
Source: custom_components/eufy_security/coordinator.py:184
Integration: Eufy Security (documentation, issues)
First occurred: 10:55:38 (1 occurrences)
Last logged: 10:55:38

Error setting up entry MYIPxxx for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

To get Eufy Security (Integration and Addon) to work, I need to restart Home Assistant.

If you need more information, I'm available

Thanks

**Comment by caelor** [comment]
I also have the same issue. I've not had chance to debug it yet, but my working theory is that the addon is still starting up. The initial error is raised from ~line 112 in coordinator.py, presumably because HA has started up but the addon hasn't yet (so it's not reachable).

The second error is because the devices have not been populated yet, but async_get_device_properties (in line 184) expects it to have been. 

My first guess at a fix would be to add a try/except guard around lines 184-213 (the whole async_get_device_properties function) and raise a ConfigEntryNotReady if an AttributeError is caught - hopefully that should cause HA to enter the retry loop that happens with the first error recorded.

**Comment by fuatakgun** [comment]
This should have been resolved in latest version of addon, please update to 0.8.0 of add-on.

**Comment by SmartM-ui** [comment]
> This should have been resolved in latest version of addon, please update to 0.8.0 of add-on.

I confirm,
with version 0.8.0 the integration works perfectly when the VM is restarted!

Thank you @fuatakgun

**Comment by caelor** [comment]
I was seeing this yesterday evening when running the 0.8.0 version of the addon. I've updated to 0.8.1 and still see it.

Versions:
- core-2022.2.2
- supervisor-2022.01.1
- HomeAssistant OS 7.2
- Add-on version 0.8.1
- Integration version 2.2.3 (via HACS)

Logs:
```
2022-02-07 04:40:12 WARNING (MainThread) [homeassistant.config_entries] Config entry 'localhost' for eufy_security integration not ready yet: Exception: Host/port is not reachable localhost 3000!; Retrying in background
...
2022-02-07 04:40:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

The HomeAssistantOS host is a VM on a Proxmox server, but all the moving parts are contained within the same VM.

@fuatakgun I suspect the integration still needs a check for None in order to work in all circumstances. Addon 0.8.0 (and 0.8.1) does **not** fix this for me.

**Comment by SmartM-ui** [comment]
Hi @caelor,
I have this configuration, with 2 cams and stopping the VM Home Assistant and restarting it (ESXi), I no longer have the error on the integration/addon:

```
    core-2022.2.2
    supervisor-2022.01.1
    HomeAssistant OS 7.2
    Add-on version 0.8.0
    Integration version 2.2.3 (via HACS)
```

I only have an error on the addon because I turn off one of the two cams via a smart switch and therefore rightly does not find it:

```
2022-02-07 09: 43: 35.358 INFO Timeout connecting to station T8410xxx
2022-02-07 09: 45: 03.235 ERROR P2PClientProtocol.lookup (): station: T8410xxx - All address lookup tentatives failed.
```

When I turn on the switch the error disappears and the webcam is perfectly integrated in Home Assistant.

When I turn it off, obviously the error reappears:

```
2022-02-07 10: 05: 21.447 WARN Station T8410xxx - Heartbeat check failed. Connection seems lost. Try to reconnect ...
2022-02-07 10: 05: 21.448 INFO Disconnected from station T8410xxx
2022-02-07 10: 05: 56.661 WARN Station T8410xxx- Tried all hosts, no connection could be established
2022-02-07 10: 05: 56.662 INFO Timeout connecting to station T8410P20210902AA
2022-02-07 10: 06: 21.665 ERROR P2PClientProtocol.lookup (): station: T8410xxx - All address lookup tentatives failed.
```

@fuatakgun  
Can I somehow solve the problem so as not to clog the log?

**Comment by SmartM-ui** [comment]
EDIT: I tried restarting Host VM again today and I have the integration problem again.

<img width="204" alt="Schermata 2022-02-07 alle 13 09 54" src="https://user-images.githubusercontent.com/63554131/152785613-8fb32874-6b72-4f84-99a2-15a4ade2b154.png">

I try to update OS, Core and Addon

**Comment by caelor** [comment]
I can confirm that I still have the problem with Addon 0.8.2.

**Comment by satyambaba** [comment]
I am facing the same issue with Addon 0.8.2 as well.

**Comment by fuatakgun** [comment]
let's follow up over here: https://github.com/fuatakgun/eufy_security/issues/258
@caelor , it is fine to get a warning at home assistant startup as add-ons are starting a bit late.
but integration is explicitly checking if push connection is established before moving forward.
As of now, I do not think we should change the logic, but let's see this after new version released.

**Comment by caelor** [comment]
Thanks. One problem is that it's not a warning that is logged, it's an AttributeException that is raised as self.devices is None and is used in an iterator.

I was just about to raise a pull request, as I've had chance to trace it through and also have been trying a potential fix which appears to work for me. The issue seems to be that if the push connection is established after the websocket to the addon has been opened, we never get informed of the devices (that's possibly an upstream bug). 

My workaround adds a guard to return False if self.devices is None (and hence fall back into what looks like the expected code flow), and also if the setup has timed out, it tears down the WebSocket connection so that the full connection is retried.

I'll submit the PR anyway, and you can decide whether to accept it. From many restarts of the VM over the last 24 hours, it's worked consistently for me, whereas without it's left the integration in a failed state ~90% of boots instead.

**Comment by fuatakgun** [comment]
> I'll submit the PR anyway, and you can decide whether to accept it. From many restarts of the VM over the last 24 hours, it's worked consistently for me, whereas without it's left the integration in a failed state ~90% of boots instead.

that is a very interesting statistics, on the other hand I haven't had this issue locally, so I will test it locally if there is a negative impact, if not, I can merge it.

**Comment by caelor** [comment]
My main concern would be about tearing down the websocket (as the other addition is just adding a guard). I didn't spot anywhere else where the ws gets closed. The aim is to put the integration back into a "retry from scratch" state when it gets into the race condition.

When I tried with just the guard (and no websocket reset), the integration remained in a `self.devices == None` state (e.g. it didn't get the message from the addon, despite the addon establishing the push connection after the integration connected). I added the full websocket teardown to fully reconnect to the addon, and that seems to have worked.

**Comment by Vyloo** [comment]
`Logger: homeassistant.config_entries
Source: custom_components/eufy_security/coordinator.py:184
Integration: Eufy Security ([documentation](https://github.com/fuatakgun/eufy_security), [issues](https://github.com/fuatakgun/eufy_security/issues))
First occurred: 12:44:52 PM (7 occurrences)
Last logged: 2:41:43 PM

Error setting up entry 0.0.0.0 for eufy_security
Error setting up entry localhost for eufy_security
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/eufy_security/__init__.py", line 51, in async_setup_entry
    await coordinator.initialize()
  File "/config/custom_components/eufy_security/coordinator.py", line 87, in initialize
    await self.set_devices()
  File "/config/custom_components/eufy_security/coordinator.py", line 163, in set_devices
    if await self.async_get_device_properties() is False:
  File "/config/custom_components/eufy_security/coordinator.py", line 184, in async_get_device_properties
    for device in self.devices.values():
AttributeError: 'NoneType' object has no attribute 'values'`


I still have this issue.
