### ISSUE TITLE
camera not available on latest bropat  0.9.0 docker container

### ISSUE THREAD

**Issue by lolouk44** [fuatakgun/eufy_security#321]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/eufy_security/blob/master/README.md

**Describe the bug**
Camera not available

**To Reproduce**
1. update to latest 0.9.0 bropat container 

**Expected behavior**
camera to be available

**Screenshots**
![image](https://user-images.githubusercontent.com/4587746/166143510-1de966af-8312-4e72-8924-a8afdc6c7729.png)

**Hardware Information about Home Assistant
Docker install

**Hardware Information about Cameras
- Camera Model: T8200 (wired 2k doorbell)
- Live Streaming Protocol: RTSP or P2p N/A

**Additional context**
Even though the camera fails, the image url returns a valid ppicture, most other sensors appear to work
Logs:
```
Logger: custom_components.eufy_security
Source: custom_components/eufy_security/websocket.py:58
Integration: Eufy Security (documentation, issues)
First occurred: 12:03:08 (3 occurrences)
Last logged: 12:03:39

eufy_security - Exception - process_messages: 'connected' - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 56, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 67, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 287, in on_message await self.process_driver_connect_response(message["connected"]) KeyError: 'connected' - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"driver_connect","result":{"result":true}}', extra='')
eufy_security - Exception - process_messages: None is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 56, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 67, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 296, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 245, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 390, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.9/enum.py", line 384, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.9/enum.py", line 702, in __new__ raise ve_exc ValueError: None is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8200N0220*****","properties":{"motionDetected":false,"personDetected":false,"personName":"","ringing":false,"name":"Doorbell","model":"T8200","serialNumber":"T8200N0220*****","type":5,"hardwareVersion":"P4","softwareVersion":"2.338","stationSerialNumber":"T8200N0220*****","pictureUrl":"[REDACTED]","notificationRing":true,"notificationMotion":true,"notificationType":2,"autoNightvision":false,"motionDetection":true,"videoStreamingQuality":1,"watermark":0,"statusLed":true,"enabled":true,"speakerVolume":148,"videoRecordingQuality":3,"chimeIndoor":true,"audioRecording":true,"videoHdr":true,"motionDetectionSensitivity":2,"videoRingRecord":1,"videoDistortionCorrection":false,"ringtoneVolume":111}}}', extra='')
eufy_security - Exception - process_messages: None is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 56, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 67, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 306, in on_message await self.process_get_station_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 260, in process_get_station_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 390, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.9/enum.py", line 384, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.9/enum.py", line 702, in __new__ raise ve_exc ValueError: None is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_station_properties","result":{"serialNumber":"T8200N0220*****","properties":{"name":"Doorbell","model":"T8200","serialNumber":"T8200N0220*****","type":5,"hardwareVersion":"P4","softwareVersion":"2.338","lanIpAddress":"192.168.9.38","macAddress":"8C858069****","timeFormat":1}}}', extra='')
```

**Comment by dexterke** [comment]
I confirm, same issue: Camera not available (camera device not being created) when using docker + Eufy T8210 Wireless Doorbell. 

* bropat/eufy-security-ws:0.9.0
* ghcr.io/home-assistant/home-assistant:stable  2022.4.7

**Comment by LucaBors** [comment]
I can confirm, same problem on mine.

**Comment by charbelsarkis** [comment]
Same here - T8114 Cameras

**Comment by mvanderheijden** [comment]
This issue is caused by a change in the properties.
I currently fixed this locally by removing `.value` from this line:
https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/const.py#L389

So it will become this:
```python
self.type_raw = get_child_value(self.properties, "type")
```

**Comment by spencerbutler** [comment]
I can confirm this fix works for T8124 and T8210.

**Comment by spencerbutler** [comment]
> This issue is caused by a change in the properties. I currently fixed this locally by removing `.value` from this line: https://github.com/fuatakgun/eufy_security/blob/master/custom_components/eufy_security/const.py#L389
> 
> So it will become this:
> 
> ```python
> self.type_raw = get_child_value(self.properties, "type")
> ```


I can confirm this fix works for T8124 and T8210.

**Comment by YarneThatsMe** [comment]
I can't seem to find this file on the docker instance. I am using UNRAID and cannot seem te find where it stores all the files. Other containers get their own files in the /appdata directory, but I cannot seems to find a eufy-security-ws directory or anything related to it, to edit the const.py file.

Any tips?

**Comment by emufan** [comment]
O.k. but I still get the error above as well every restart:

```
KeyError: 'connected'
```

**Comment by mvanderheijden** [comment]
> O.k. but I still get the error above as well every restart:
> 
> ```
> KeyError: 'connected'
> ```

I noticed the same error. Created a PR with the fix

**Comment by cdnninja** [comment]
Thanks for the contribution.  I have merged that fix.

**Comment by YarneThatsMe** [comment]
When will the new version get released with this fixed issue? I am still facing the problem...
