### ISSUE TITLE
HomeBase 3 (S380) not working

### ISSUE THREAD

**Issue by michaeleberhardt** [fuatakgun/eufy_security#473]
With introduction of Homebase 3 it seems like it is not compatible yet.
Log:

2022-10-01 16:01:15.310  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-10-01 16:01:25.563  INFO  Push notification connection successfully established 
2022-10-01 16:01:31.968  ERROR P2PClientProtocol.lookup(): station: T8030P23222xxxxx - All address lookup tentatives failed. 
2022-10-01 16:01:31.970  INFO  Timeout connecting to station T8030P23222xxxxx
2022-10-01 16:01:51.979  ERROR P2PClientProtocol.lookup(): station: T8030P23222xxxxx - All address lookup tentatives failed. 
2022-10-01 16:01:51.980  INFO  Timeout connecting to station T8030P23222xxxxx
2022-10-01 16:02:16.990  ERROR P2PClientProtocol.lookup(): station: T8030P23222xxxxx - All address lookup tentatives failed. 
2022-10-01 16:02:16.991  INFO  Timeout connecting to station T8030P23222xxxxx
2022-10-01 16:02:52.010  ERROR P2PClientProtocol.lookup(): station: T8030P23222xxxxx - All address lookup tentatives failed. 
2022-10-01 16:02:52.010  INFO  Timeout connecting to station T8030P23222xxxxx
2022-10-01 16:03:37.022  ERROR P2PClientProtocol.lookup(): station: T8030P23222xxxxx - All address lookup tentatives failed. 
2022-10-01 16:03:37.022  INFO  Timeout connecting to station T8030P23222xxxxx
2022-10-01 16:04:32.063  ERROR P2PClientProtocol.lookup(): station: T8030P23222xxxxx - All address lookup tentatives failed. 
2022-10-01 16:04:32.064  INFO  Timeout connecting to station T8030P23222xxxxx

Are there plans to support HomeBase 3?

Thanks a lot & best regards,
Michael :-)

**Comment by Chahk** [comment]
I'm getting the following error in the logs:

`eufy_security - Exception - process_messages: 19 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 260, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 446, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 19 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8160P11222603BE","properties":{"name":"Backyard","model":"T8160","serialNumber":"T8160P11222603BE","type":19,"hardwareVersion":"P1","softwareVersion":"3.1.7.8","stationSerialNumber":"T8030P1322260CD9"}}}', extra='')`

**Comment by ajma** [comment]
Don't forget the S300 (3C) too

**Comment by ajma** [comment]
The PR got merged so are we able to create a new release for this?

**Comment by cdnninja** [comment]
Done.

**Comment by ajma** [comment]
Those PRs didn't seem like it was enough to get the homebase 3 support. I've updated my plugin and it's still not showing the new homebase.

**Comment by ajma** [comment]
I figured what that I did. I thought the device_type were defined by this project but they're in fact returned by the API, so I made another update to fix this: #491 after this gets merged, can we please create new release for this. It should fix the issue for me and @aszymanik

**Comment by cdnninja** [comment]
I am going to re-open this until confirmed working.  I noticed this on the underlying library: https://github.com/bropat/eufy-security-ws/issues/139

**Comment by cdnninja** [comment]
It may not be related though.

**Comment by KyleDoherty1** [comment]
I am still experience the same issue:

```
2022-10-24 12:29:24.993  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-10-24 12:29:27.994  INFO  Push notification connection closed 
2022-10-24 12:29:35.361  INFO  Push notification connection successfully established 
2022-10-24 12:29:35.364  INFO  Push notification connection successfully established 
2022-10-24 12:29:50.171  ERROR P2PClientProtocol.lookup(): station: T8030P2322290D06 - All address lookup tentatives failed. 
2022-10-24 12:29:50.175  INFO  Timeout connecting to station T8030P2322290D06 
2022-10-24 12:30:10.185  ERROR P2PClientProtocol.lookup(): station: T8030P2322290D06 - All address lookup tentatives failed. 
2022-10-24 12:30:10.186  INFO  Timeout connecting to station T8030P2322290D06 
2022-10-24 12:30:35.192  ERROR P2PClientProtocol.lookup(): station: T8030P2322290D06 - All address lookup tentatives failed. 
2022-10-24 12:30:35.195  INFO  Timeout connecting to station T8030P2322290D06 
```

**Comment by hotmachina** [comment]
Same issue, here is my output if useful.

2022-10-24 17:07:13.258  INFO  Timeout connecting to station T8122P102135104E 
2022-10-24 17:11:34.042  ERROR P2PClientProtocol.lookup(): station: T8030P2322290C13 - All address lookup tentatives failed. 
2022-10-24 17:11:34.043  INFO  Timeout connecting to station T8030P2322290C13 
2022-10-24 17:17:28.459  ERROR P2PClientProtocol.lookup(): station: T8122P102135104E - All address lookup tentatives failed. 
2022-10-24 17:17:28.460  INFO  Timeout connecting to station T8122P102135104E 
2022-10-24 17:21:35.181  ERROR P2PClientProtocol.lookup(): station: T8030P2322290C13 - All address lookup tentatives failed. 
2022-10-24 17:21:35.182  INFO  Timeout connecting to station T8030P2322290C13 
2022-10-24 17:27:43.467  ERROR P2PClientProtocol.lookup(): station: T8122P102135104E - All address lookup tentatives failed. 
2022-10-24 17:27:43.467  INFO  Timeout connecting to station T8122P102135104E 
2022-10-24 17:31:36.040  ERROR P2PClientProtocol.lookup(): station: T8030P2322290C13 - All address lookup tentatives failed. 
2022-10-24 17:31:36.041  INFO  Timeout connecting to station T8030P2322290C13 
2022-10-24 17:37:58.475  ERROR P2PClientProtocol.lookup(): station: T8122P102135104E - All address lookup tentatives failed. 
2022-10-24 17:37:58.475  INFO  Timeout connecting to station T8122P102135104E 
2022-10-24 17:41:37.038  ERROR P2PClientProtocol.lookup(): station: T8030P2322290C13 - All address lookup tentatives failed.

**Comment by hotmachina** [comment]
Also have this later in the log:

 NotSupportedError  This functionality is not implemented or supported by T8160P2122320971
error stack:
• station.ts:2917 startLivestream
    node_modules/eufy-security-client/src/http/station.ts:2917:19
• message_handler.ts:124 handle
    src/lib/device/message_handler.ts:124:39
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21

**Comment by KyleDoherty1** [comment]
@cdnninja any update? I can help with the coding if needs be just need to get up to speed with how HA and these addons using npm packages.

**Comment by cdnninja** [comment]
> @cdnninja any update? I can help with the coding if needs be just need to get up to speed with how HA and these addons using npm packages.

I think this is a bropat issue as linked above but don't know the code well enough to know for sure.  @fuatakgun  would know.

**Comment by KyleDoherty1** [comment]
@cdnninja @fuatakgun any update on this one?

**Comment by fuatakgun** [comment]
Did you check with latest integration version?

**Comment by KyleDoherty1** [comment]
@fuatakgun yeah few things still not working like:

- https://github.com/fuatakgun/eufy_security/issues/536
- https://github.com/fuatakgun/eufy_security/issues/495

Has there been updates to address the above that I have missed?

**Comment by fuatakgun** [comment]
if you are having issues inside add-on even in 1.3.0, please raise an issue on eufy-security-ws repository
