### ISSUE TITLE
Camera becomes unavailable after stopping stream

### ISSUE THREAD

**Issue by mrwhite31** [fuatakgun/eufy_security#492]
**Describe the bug**
I am starting an RTSP stream by calling the service camera.turn_on or eufy_security.start_rtsp_livestream. Then cast this camera to a Google Nest Hub, TV or display it directly through the Media Browser in HA. The stream works correctly.
But after stopping the stream with camera.turn_off or eufy_security.stop_rtsp_livestream, this and only this camera becomes "unavailable" and another stream cannot be started (see screenshot). As seen in the log of the screenshot it is trying to reconnect somehow, but becoming unavailable again.
It does not happen when starting and stoping a stream without effectively displaying it somewhere.

**To Reproduce**
1. start a stream with eufy_security.start_rtsp_livestream
2. Cast or display the stream somewhere
3. stop the stream with eufy_security.stop_rtsp_livestream
4. Go to the camera under Devices. It shows unavailable
5. Try to start another stream on the same camera, which is not possible
6. Restarting the Eufy Security Integration brings the camera back to Idle

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46862347/197524413-cd61da7b-1a76-495e-9614-1e41ce64369d.png)

**Hardware Information about Home Assistant
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest
Odroid N2+
Eufy Security Addon v0.9.4
Eufy Security Integration v2.8.1
RTSP Simple Server Add-on v0.17.6

**Hardware Information about Cameras
- Camera Model: 2c
- Live Streaming Protocol: RTSP

**Additional context**
In the log I can see the following:
Error from stream worker: Stream ended; no additional packets
Error from stream worker: Error opening stream (HTTP_NOT_FOUND, Server returned 404 Not Found) rtsp://****:****@192.168.x.xx/live2

**Comment by fuatakgun** [comment]
this happens to me some time to time but not always. Can you find a way to reproduce all the time?

**Comment by mrwhite31** [comment]
Yes, it happens every time.Am 05.11.2022 um 17:56 schrieb Fuat Akgün ***@***.***>:﻿
this happens to me some time to time but not always. Can you find a way to reproduce all the time?

**Comment by fuatakgun** [comment]
you are right, will be fixed in new major release of integration

**Comment by mrwhite31** [comment]
Thanks!

**Comment by fuatakgun** [comment]
Main reason for this, when streaming becomes stopped, background stream which is managed by home assistant becomes unavailable, and for some reason, it is decided that background stream state is setting the camera state.

I will remove this functionality (setting availability of camera based on stream availability) because on demand streaming systems should not make this as they are continuous streaming.

**Comment by fuatakgun** [comment]
Actually, let me fix it now, no need to wait for next release

**Comment by fuatakgun** [comment]
should be fixed in new version

**Comment by Cyclone47** [comment]
Hi @fuatakgun
Is this updated already? Just making sure as I'm still experiencing this behavior.

Thanks!

**Comment by fuatakgun** [comment]
Yes, in alpha version

**Comment by fuatakgun** [comment]
Or you can also stay in current release and make it fixed. No enforcement for alpha release

**Comment by fuatakgun** [comment]
https://github.com/fuatakgun/eufy_security/releases/tag/v2.10.0

**Comment by Cyclone47** [comment]
> https://github.com/fuatakgun/eufy_security/releases/tag/v2.10.0

Seems like I already had this version. Not sure if it's the same issue; but for me it goes as following.
I use:

Trigger -> When Doorbell Ringing Sensor Changes to True
Actions -> Play Doorbell on Google Hub

This seems to work, but after a random while it stops working. My workaround to get it fixed is to use: 
Conditions: If Doorbell is streaming then camera -> Turn Off Deurbel | camera -> Turn on Deurbel | Play Doorbell on Google Hub.

Any ideas?

**Comment by fuatakgun** [comment]
So, camera is still going into unavailable?

**Comment by Cyclone47** [comment]
> So, camera is still going into unavailable?

I am not  sure if it's the same exact issue, but for me it sometimes becomes idle and I then get a notification saying:
Eufy Security - Not Supported - RTSP
Camera Deurbel does not support RTSP

**Comment by fuatakgun** [comment]
no it is not an issue and P2P streaming is very problematic, sometimes it can stream for hours, sometimes couple of seconds because of packet drops, and there is no solution other than restarting the stream.

Are you sure, your camera supports RTSP stream?

**Comment by Cyclone47** [comment]
> no it is not an issue and P2P streaming is very problematic, sometimes it can stream for hours, sometimes couple of seconds because of packet drops, and there is no solution other than restarting the stream.
> 
> Are you sure, your camera supports RTSP stream?

I'm using the Eufy Doorbell T8200. Officially no.. but I have had great hopes with this integration and the way it works so far. 
After reloading the Eufy Addon it works again. So perhaps I should trigger this reload when the streaming sensor goes unknown?

**Comment by fuatakgun** [comment]
are you on Alpha release (v5.x) or master release? (v2.x)

In any case, you can call turn_off and turn_on again, it should work?

**Comment by fuatakgun** [comment]
Sorry, instead of using turn_on and turn_off, focus on using start_p2p_livestream and stop_p2p_livestream

**Comment by Cyclone47** [comment]
> Sorry, instead of using turn_on and turn_off, focus on using start_p2p_livestream and stop_p2p_livestream
That seems to work as workaround! Thanks 👍 

Eufy Security Add-on
Current version: 1.3.0 

Manifest.json shows:   "version": "2.10.0"

**Comment by fuatakgun** [comment]
you can migrate into v5 versions, I am expecting better performance and more stability
